/**
 * Netlify build: writes config.js with live backend URL from env var.
 * Set in Netlify → Site settings → Environment variables:
 *   PORTFOLIO_API_URL = https://your-app.onrender.com
 */
const fs = require("fs");
const path = require("path");

const apiUrl = (process.env.PORTFOLIO_API_URL || "").replace(/\/$/, "");

const content = `/**
 * Auto-generated by Netlify build — do not edit manually on live site.
 */
window.PORTFOLIO_CONFIG = {
  API_URL: "${apiUrl}"
};
`;

fs.writeFileSync(path.join(__dirname, "..", "config.js"), content, "utf8");
console.log(`[build] config.js written — API_URL: ${apiUrl || "(same origin)"}`);
